config/routes.rb
Rails.application.routes.draw do
  devise_for :users, path: '', path_names: { sign_in: 'login', sign_out: 'logout'}, controllers: { registrations: "user_registrations" }
  resources :users
  resources :products do
    resources :comments
  end
  resources :orders, only: [:index, :show, :create, :destroy]
  mount ActionCable.server => '/cable'
  get 'static_pages/index'

  get 'static_pages/about'

  get 'static_pages/contact'

  post 'payments/create'

  post 'static_pages/thank_you'

  root 'static_pages#landing_page'
  # For details on the DSL available within this file, see http://guides.rubyonrails.org/routing.html
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>

    <meta name="viewport" content="width=device-width, initial-scale=1">
    <%= csrf_meta_tags %>

    <link rel="stylesheet" href="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/css/bootstrap.min.css" integrity="sha384-BVYiiSIFeK1dGmJRAkycuHAHRg32OmUcww7on3RYdg4Va+PmSTsz/K68vbdEjh4u" crossorigin="anonymous">
    <%= stylesheet_link_tag    'application', media: 'all', 'data-turbolinks-track': 'reload' %>

    <%= javascript_include_tag 'application', 'data-turbolinks-track': 'reload' %>
    <script src="https://maxcdn.bootstrapcdn.com/bootstrap/3.3.7/js/bootstrap.min.js" integrity="sha384-Tc5IQib027qvyjSMfHjOMaLkfuWVxZxUPnCJA7l2mCWNIpG9mGCD8wGNIcPD7Txa" crossorigin="anonymous"></script>

    <title>Klaxon</title>

  </head>

  <body>
      <%= link_to image_tag("Klaxon-Logo.png", class: "img-responsive brand", alt: "Klaxon Logo"), root_path %>
      <nav class="navbar navbar-inverse">
        <div>
          <div class="navbar-header" id="hamburger">
            <button type="button" class="navbar-toggle collapsed pull-left" data-toggle="collapse" data-target=".navbar-collapse">
              <span class="sr-only">Toggle Navigations</span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
              <span class="icon-bar"></span>
            </button>
          </div><!--end hamburger-->

          <div class="collapse navbar-collapse" id="main-nav">
            <ul class="nav navbar-nav" id="nav-links">
              <li id="Products"><%= link_to 'Products', products_path %></li>
              <li id="About"><%= link_to 'About', static_pages_about_path %></li>
              <li id="Contact"><%= link_to 'Contact', static_pages_contact_path %></li>
            </ul>
            <div class="pull-right" id="register">
              <% if user_signed_in? %>
                <%= link_to('Logout', destroy_user_session_path, method: :delete, :class=>"btn btn-warning btnLogin") %>
              <% else %>
                <%= link_to('Login', new_user_session_path, :class=>"btn btn-warning btnLogin") %>
                <%= link_to('Sign up', new_user_registration_path, :class=>"btn btn-outline-warning btnRegister") %>
              <% end %>
            </div>

            <div class="form-inline form-group" role="search" id="search-box">
              <%= form_tag("/products", method: "get") do %>
                <%= search_field_tag(:q, "Search", class: "form-control") %>
                <%= submit_tag("Search", class: "btn btn-default") %>
              <% end %><!--end search box-->
            </div><!--end search form-->
          </div><!--end main nav-->
        </div><!--end -->
      </nav><!--end top navigation-->
      
      <!--Flash Notice Tags-->
      <% if notice %>
        <div id="notice" class="alert alert-success"><%= notice %></div>
      <% end %>
      <% if alert %>
        <div id="alert" class="alert alert-danger"><%= alert %></div>
      <% end %>

      <%= yield %>

      <footer class="footer">
        <div class="container" id="header">
          <div class="content">
            <div class="row">
              <div class="col-md-4" id="Social">
                <h5>Get Social</h5>
                <p>Facebook Instagram Pinterest</p>
              </div>
              <div class="col-md-4" id="Instagram">
                <h5>Instagram Feed</h5>
                <div class="gallery-feed">
                  <%= image_tag("Wms-Rocket.png", class: "img-responsive", alt: "Social Image", width: "50", height: "50") %>
                </div>
              </div>
              <div class="col-md-4" id="News">
                <h5>Get the Newsletter</h5>
                <p>We promise to only send exciting things.</p>
                <form id="email_signup_footer">
                  <input type="email" name="email" class="validate_email" placeholder="your email address">
                  <button type="submit" class="submit_button">Sign Up</button>
                </form>
              </div>
            </div><!--end row-->
            <hr>
            <ul class="navigation pull-left">
              <li><a href="#">Home</a></li>
              <li><a href="#">Shipping</a></li>
              <li><a href="#">FAQ</a></li>
              <li><a href="#">Contact</a></li>
            </ul>
          </div><!--end content-->
            <div class="copyright pull-right">
              &copy; 2017 Klaxon
            </div><!--end copyright-->
        </div><!--end header-->
      </footer>
  </body>
</html>